default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: multi-level-resources_development

test:
  <<: *default
  database: multi-level-resources_test

production:
  <<: *default
  database: multi-level-resources_production
